### ISSUE TITLE
Simple Request if its not too much.

### ISSUE THREAD

**Issue by Jieiku** [gonzomir/minimal-share-buttons#2]
The small list of supported social networks is Nearly Perfect for me! I only use the most common ones which your plugin supports, all EXCEPT Pinterest. I know you have to draw a line on this subject someplace, but pinterest is actually pretty common, so I am hoping there is a chance you might include Pinterest.

A Shortcode would be great.

I am now using your minimal-share-buttons with "Open Graph Meta Tags by Heateor" So that descriptions and image previews get properly set.

If you have any alternative to "Open Graph Meta Tags by Heateor" please do let me know, I like to try whatever I can find if its more lightweight.

**Comment by gonzomir** [comment]
Hi, @xekon, I have had other requests for Pinterest, and since G+ is shutting down I am going to update the list of supported networks. 

For showing the buttons on WooCommerce products - I just found a bug in the way I'm listing the available post types and I'll fix it in a new release the following days.

I haven't thought about adding shortcode, although it seams to be a good idea. Would you mind adding another issue so that I can track progress there and leave this for social medias? 

The latest version of the plugin has Gutenberg block available in the Widgets category, so you can use that if you have Gutenberg installed or after WordPress 5.0 is released.

As for adding OG tags I don't have personal favourite, people you all kinds of SEO plugins that do that among other things. If "Open Graph Meta Tags by Heateor" suits you, than go with it. :smile:

**Comment by Jieiku** [comment]
Thank you for the reply, I have opened another issue per your request for the shortcode feature

Also, looking forward to your next version!

**Comment by gonzomir** [comment]
I just released new version that allows the sharing buttons to be shown on WooCommerce products and any other public post type that supports editor.
